### PR TITLE
Mannheim germany blog post

### PR DESCRIPTION
**Pull request by drewda**

### CODE REVIEW

**Comment by drewda** [comment]
@stevevance quite the story of institutional hierarchies. A few small suggestions and edits before we publish:

- "Trams and buses run frequently to and from the *haltestelle* (stop)" <-- perhaps a problem with Markdown formatting
- Link off to QGIS site
- Link to the Route Stop Pattern docs ( https://transit.land/documentation/datastore/routes-and-route-stop-patterns.html ) or to its intro blog post ( https://transit.land/news/2016/04/15/transitland-route-geometries.html )
- Let's leave this out for now: "Our upcoming Mobility Explorer will make it easier than downloading files and using third-party apps to find this kind of specific transit data."
- "Once I have the stops’ onestopId I can plug that into the" --> Why don't you change that to "Onestop ID" (without code formatting) and link it to https://transit.land/documentation/onestop-id-scheme/
- Did you ever point to https://transit.land/feed-registry/operators/o-u0y1-rhein~neckar~verkehrgmbhrnv ? That could be another "jumping off point" to send readers to at the end.
- The post is still dated for Sept. 1. Should we aim for tomorrow or Thursday? In either case, please rename the file.

**Comment by stevevance** [comment]
I'll address all of those. 

What does this mean, @drewda?

````
"Trams and buses run frequently to and from the haltestelle (stop)" <-- perhaps a problem with Markdown formatting
````

**Comment by drewda** [comment]
Thanks, @stevevance 

Re the italics issues, this is what I see on precog. I suspect it's just an issue of trying to use Markdown syntax within an HTML block:

german transit s tight integration ensures timely connections in small cities transitland 2016-09-07 11-25-08

**Comment by drewda** [comment]
@stevevance a few more items to note:

- @kevinkreiser (who happens to know some German) read and pointed out:
    - RegioBahn --> Regionalbahn
    - RegioExpress --> RegionalExpress
- also note that when we merge this out to the production server, the URL for the Tangram scene file should be a `https://transit.land...` URL. Just had to fix that on the Morgantown post (https://github.com/transitland/www-transit-land/pull/226/files)

**Comment by stevevance** [comment]
@drewda I pushed the changes.

**Comment by drewda** [comment]
@stevevance 👍

**Pull request merged**
