### PR TITLE
Route updates

### LINKED ISSUE #268: update docs about Route and RouteStopPattern models
- [x] a paragraph about route model
- [x] table of route model properties
- [x] table of route vehicle types https://github.com/transitland/www-transit-land/issues/179
- [x] explanation of representative route geometry (with a graphic?)
- [x] updated and simplified explanation of RSP distance calculation
- [x] explain when low-quality distances are left off RSPs and SSPs
- [x] update RSP response example to not include http://dev.transit.land
- [x] remove "is_modified"
- [x] clarify that "is_generated" means the initial import was generated; RSPs can be edited and still remain "is_generated=true"

### PR DESCRIPTION
**Pull request by doublestranded**
closes #268 

on precog: https://precog.mapzen.com/transitland/www-transit-land/route-updates/documentation/datastore/routes-and-route-stop-patterns.html#vehicle_types

### CODE REVIEW

**Comment by kkowalsky** [comment]
The Vehicle Types section is linked, but doesn't have a path... Is that intentional? Also vehicle types 1702 and 405 are the best. 

add 'a' before 'Douglas-Peucker algorithm' and link to a page (for those of us who don't know what that is). 

In the Distance calculation heuristic algorithm section, :100: for explaining the algorithm behind stop patterns, that's immensely useful. There's a spelling error after that paragraph, "Transitland logs inaccuraties" <-- should be _inaccuracies_

**Comment by kkowalsky** [comment]
After those two spelling checks, you're all set by the docs team :smile:

**Comment by drewda** [comment]
This is looking good, @doublestranded. And thanks for your close read, @kkowalsky.

A few improvements we should do before merging:
- [ ] in the vehicle types table, add in the basic vehicle types: https://github.com/transitland/gtfs/blob/master/lib/gtfs/route.rb#L15-L22
- [ ] in the vehicle types table, also mention the strings that Datastore API takes in queries (e.g., `railway_service` instead of `1001) and link to example queries
- [ ] replace mention of RSP `is_generated` with the new `geometry_source` enum being added in https://github.com/transitland/transitland-datastore/pull/994

I can work on the first two of those items.

**Comment by doublestranded** [comment]
Thanks @kkowalsky and @drewda! Good eyes. I've made the edits (using the Douglas-Peucker Wikipedia page for stability. Plus it has a good graphic). Thanks for making the vehicle types section more complete @drewda !

**Pull request merged**
